#!/usr/bin/env bash
#
# bootstrap installs things.
DIR_SCRIPT="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
DIR_ROOT="$(dirname "$DIR_SCRIPT")"
DIR_HOME="$DIR_ROOT/home"

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

install_dotfiles () {
  info 'installing dotfiles'

  mkdir -p $HOME/bin/

  info "Setting up .bash_profile"
  ln -s -f $DIR_HOME/.bash_profile $HOME/.bash_profile

  info "Setting up .tmux.conf"
  ln -s -f $DIR_HOME/.tmux.conf $HOME/.tmux.conf

  info "Setting up .bash_aliases"
  ln -s -f $DIR_HOME/.bash_aliases $HOME/.bash_aliases

  info "Setting up a general base .gitconfig"
  ln -s -f $DIR_HOME/.gitconfig $HOME/.gitconfig
  
  if [[ ! -e $HOME/.oh-my-zsh ]]; then
      info "Setting up oh-my-zsh"
      sh $DIR_SCRIPT/install-zsh.sh
  fi

  info "Setting up custom.zsh"
  rm -f  $HOME/.oh-my-zsh/custom/custom.zsh
  ln -s -f $DIR_HOME/.oh-my-zsh/custom/custom.zsh $HOME/.oh-my-zsh/custom/custom.zsh
}

install_dotfiles

echo ''
echo '  All installed!'
