#!/usr/bin/env bash
#
# bootstrap installs things.
DIR_SCRIPT="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
DIR_ROOT="$(dirname "$DIR_SCRIPT")"
DIR_HOME="$DIR_ROOT/home"

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

install_dotfiles () {
  info 'installing dotfiles'

  for src in $(find -H "$DIR_HOME" -maxdepth 2 -name '*' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    ln -s "$src" "$dst"
  done
}

install_dotfiles

echo ''
echo '  All installed!'
